<?php

$labels = array(
	'alternativeemail' => 'Alternative email',
	'forgotpassword' => 'Forgot my password',
	'passwordrecovery' => 'Forgot Password',
	'email_subject' => 'Instructions to generate new password',
	'admin_alert_email_subject' => 'Request for new password',
	'pwreminder' => 'Password Reminder',
	'forgot_passwordenabled' => 'Reminder enabled',
	'forgot_passwordisenabled' => 'Reminder is enabled',
	'forgot_passworddisabled' => 'Reminder is disabled',
	'forgot_passwordaddress' => 'Send Password to',
	'forgot_passwordquestion' => 'Secret Question',
	'forgot_passwordanswer' => 'Secret Answer',
	'forgot_passwordanswerconfirm' => 'Confirm Secret Answer',
	'forgot_passwordaddidentity' => 'Please add an identity',
	'forgot_passwordadd' => 'add',
	'forgot_passwordresetpw' => 'Send',
	'forgot_passwordexit' => 'Cancel',
	'new_password' => 'New password',
	'new_password_confirmation' => 'Repeat password',
	'no_alternative_email_warning' => 'You need to set an alternative email',
	'click_here' => 'Click here'
);

$messages = array(
	'forgot_passwordquestionempty' => 'Please enter your Secret Question',
	'forgot_passworduserempty' => 'Please enter your email',
	'forgot_passwordanswerempty' => 'Please enter your Secret Answer',
	'forgot_passwordanswernotmatch' => 'Secret Answer does not match',
	'forgot_passwordactive' => 'Password Reminder will be enabled',
	'forgot_passwordinactive' => 'Password Reminder is disabled',
	'forgot_passwordusernotfound' => 'User not found',
	'forgot_passwordimcomplete' => 'Your Reminder Settings are incomplete. Please contact the Administrator',
	'forgot_passwordfailed' => 'Secret Answer is incorrect.',
	'sendingfailed' => 'An error ocurred, try again later or contact the administrator',
	'checkaccount' => 'And email has been sent to your alternative email account with instructions to reset your password',
	'senttoadmin' => 'You haven\'t set an alternative email, instead your administrator has been notified',
	'autobanned' => 'Access is temporarilly locked (too many invalid login attempts). Please try later.',
	'nodeleteforgot_passwordaddress' => 'This identity is linked to your Password reminder.',
	'invalidtoken' => 'Invalid token',
	'password_confirmation_invalid' => 'Password confirmation invalid',
	'password_changed' => 'Password changed successfully',
	'password_not_changed' => 'An error ocurred, try again later or contact the administrator',
	'notice_no_alternative_email_warning' => 'You don\'t have an alternative email set, %s to set.',
	'alternative_email_updated' => 'Your alternative email has been changed',
	'alternative_email_invalid' => 'Invalid alternative email'
);