<?php

$labels = array(
	'forgotpassword' => 'Esqueci minha senha',
	'passwordrecovery' => 'Forgot Password',
	'email_subject' => 'Instruções para gerar nova senha',
	'admin_alert_email_subject' => 'Solicitação de troca de senha',
	'pwreminder' => 'Password Reminder',
	'forgot_passwordenabled' => 'Reminder enabled',
	'forgot_passwordisenabled' => 'Reminder is enabled',
	'forgot_passworddisabled' => 'Reminder is disabled',
	'forgot_passwordaddress' => 'Send Password to',
	'forgot_passwordquestion' => 'Secret Question',
	'forgot_passwordanswer' => 'Secret Answer',
	'forgot_passwordanswerconfirm' => 'Confirm Secret Answer',
	'forgot_passwordaddidentity' => 'Please add an identity',
	'forgot_passwordadd' => 'add',
	'forgot_passwordresetpw' => 'Enviar',
	'forgot_passwordexit' => 'Cancelar',
	'new_password' => 'Nova senha',
	'new_password_confirmation' => 'Confirmação',
	'no_alternative_email_warning' => 'Cadastre um email alternativo.',
	'click_here' => 'clique aqui'
);

$messages = array(
	'forgot_passwordquestionempty' => 'Please enter your Secret Question',
	'forgot_passworduserempty' => 'Por favor informe seu E-mail',
	'forgot_passwordanswerempty' => 'Please enter your Secret Answer',
	'forgot_passwordanswernotmatch' => 'Secret Answer does not match',
	'forgot_passwordactive' => 'Password Reminder will be enabled',
	'forgot_passwordinactive' => 'Password Reminder is disabled',
	'forgot_passwordusernotfound' => 'Usuário não encontrado',
	'forgot_passwordimcomplete' => 'Your Reminder Settings are incomplete. Please contact the Administrator',
	'forgot_passwordfailed' => 'Secret Answer is incorrect.',
	'sendingfailed' => 'Ocorreu um erro ao enviar o email com instruções para gerar uma nova senha. Por favor tente novamente mais tarde',
	'checkaccount' => 'Foi enviado um email com instruções para gerar uma nova senha para seu email alternativo.',
	'senttoadmin' => 'Sua conta não possui um email alternativo cadastrado, por isso foi enviado um email para o Administrador trocar sua senha.',
	'autobanned' => 'Access is temporarilly locked (too much invalid login attempts). Please try later.',
	'nodeleteforgot_passwordaddress' => 'This identity is linked to your Password reminder.',
	'invalidtoken' => 'Token inválido.',
	'password_confirmation_invalid' => 'Confirmação de senha inválida',
	'password_changed' => 'Senha alterada com sucesso.',
	'password_not_changed' => 'Ocorreu um erro ao alterar a senha. Por favor tente novamente mais tarde.',
	'notice_no_alternative_email_warning' => 'Você não possui um email alternativo cadastrado, %s para cadastrar.',
	'alternative_email_updated' => 'Seu email alternativo foi alterado.',
	'alternative_email_invalid' => 'Informe um email alternativo válido.'
);