<?php

$labels = array(
	'alternativeemail' => 'Email alternativo',
	'forgotpassword' => 'Olvidé mi contraseña',
	'passwordrecovery' => 'Olvidé mi contraseña',
	'email_subject' => 'Instrucciones para definir una nueva contraseña',
	'admin_alert_email_subject' => 'Solicitud de nueva contraseña',
	'pwreminder' => 'Recordatorio de Contraseña',
	'forgot_passwordenabled' => 'Reminder enabled',
	'forgot_passwordisenabled' => 'Recordatorio habilitado',
	'forgot_passworddisabled' => 'Recordatorio deshabilitado',
	'forgot_passwordaddress' => 'Enviar contraseña a',
	'forgot_passwordquestion' => 'Pregunta secreta',
	'forgot_passwordanswer' => 'Respuesta secreta',
	'forgot_passwordanswerconfirm' => 'Confirmar respuesta secreta',
	'forgot_passwordaddidentity' => 'Por favor, añada una identidad',
	'forgot_passwordadd' => 'Agregar',
	'forgot_passwordresetpw' => 'Enviar',
	'forgot_passwordexit' => 'Cancelar',
	'new_password' => 'Nueva contraseña',
	'new_password_confirmation' => 'Repita la contraseña',
	'no_alternative_email_warning' => 'Es necesario establecer un correo electrónico alternativo.',
	'click_here' => 'haga clic aquí'
);

$messages = array(
	'forgot_passwordquestionempty' => 'Introduzca su pregunta secreta',
	'forgot_passworduserempty' => 'Introduzca su dirección de correo electrónico',
	'forgot_passwordanswerempty' => 'Introduzca su respuesta secreta',
	'forgot_passwordanswernotmatch' => 'Respuesta secreta no coincide',
	'forgot_passwordactive' => 'Recordatorio de contraseña se activará',
	'forgot_passwordinactive' => 'Recordatorio de contraseña está deshabilitada',
	'forgot_passwordusernotfound' => 'Usuario no encontrado',
	'forgot_passwordimcomplete' => 'De los ajustes de recordatorio están incompletos. Por favor, póngase en contacto con el Administrador',
	'forgot_passwordfailed' => 'Respuesta secreta es incorrecta.',
	'sendingfailed' => 'Se produjo un error, inténtalo de nuevo más tarde o póngase en contacto con el administrador',
	'checkaccount' => 'Un correo electrónico ha sido enviado a su E-mail alternativo con instrucciones para restablecer su contraseña',
	'senttoadmin' => 'Ud no ha definido un correo alternativo. Se ha notificado al administrador sobre este hecho.',
	'autobanned' => 'El acceso bloqueado temporalmente (demasiados intentos no válidos). Por favor, intente más tarde.',
	'nodeleteforgot_passwordaddress' => 'Esta identidad está ligada a su recordatorio de contraseña.',
	'invalidtoken' => 'Token inválido.',
	'password_confirmation_invalid' => 'Confirmación de la contraseña no es válida',
	'password_changed' => 'Contraseña cambiada con éxito',
	'password_not_changed' => 'Se ha producido un error, inténtalo de nuevo más tarde.',
	'notice_no_alternative_email_warning' => 'No ha configurado un correo electrónico altermativo, %s y selecciones su identidad para registrarlo.',
	'alternative_email_updated' => 'Su dirección de correo electrónico alternativa ha cambiado.',
	'alternative_email_invalid' => 'Correo electrónico alternativo no válido'
);
